#  polyglot.toml -*- mode: toml-ts-mode -*-
#  Summary: Describes polyglot settings
#
#  '{}' in a string refers to the project name
#  eg: project 'blah', {}.sln -> blah.sln
#  Tags:
#

[polyglot]

[polyglot.general]
files = [
  "polyglot.toml", "VERSION.toml", "LICENSE",
  ".lenvs", ".gitignore", ".editorconfig",
  ".rgignore", "checklist.md", ".related",
  "repo-layout.md"
]
dirs  = [
      ".tasks", ".temp", "src/_notes",
      "src/_tests", "src/_data"
]

#  Environment --------------------------------------------------

[polyglot.direnv]
config = [".envrc"]

[polyglot.asdf]
files = [".asdf.plugins", ".tool-versions"]

#  CI Workflows --------------------------------------------------

[polyglot.github]
dirs = [".github"]

[polyglot.gitlab]
files = [".gitlab-ci.yml"]
dirs  = [".gitlab"]

[polyglot.precommit]
files = [".pre-commit-config.yaml"]

[polyglot.tox]
files  = ["tox.toml"]

#  Languages --------------------------------------------------

[polyglot.python]
suffixes  = [".py"]
config    = ["pyproject.toml", "ruff.toml", "uv.lock"]
prefix    = "py_"
active    = []

[polyglot.rust]
suffixes  = [".rs"]
config    = [
          "build.rs", "Cargo.toml", ".cargo/config.toml",
          "clippy.toml" "rust-toolchain.toml", ".rustfmt.toml",
          "Cargo.lock",
]
prefix    = "rs_"
active    = []

[polyglot.lisp]
suffixes  = [".el"]
config    = ["Eask"]
prefix    = "el_"
active    = []

[polyglot.asp]
suffixes  = [".lp"]
config    = []
prefix    = "asp_"
active    = []

[polyglot.dotnet]
config    = ["{}.sln", "nuget.config", "Directory.Build.props"]
active    = []

[polyglot.dotnet-csharp]
suffixes  = [".cs", ".csproj"]
prefix    = "cs_"
active    = []

[polyglot.dotnet-fsharp]
suffixes  = [".fs", ".fsproj"]
prefix    = "fs_"
active    = []

[polyglot.elixir]
suffixes  = [".exs", ".ex"]
config    = ["mix.ex" "config.exs", ".formatter.exs"]
prefix    = "ex_"
active    = []

[polyglot.godot]
suffixes  = [".gd", ".tscn"]
config    = ["project.godot", "export_presets.cfg", "preferred_profile.build"]
prefix    = "gd_"
active    = []

[polyglot.kotlin]
suffixes  = [".kt", ".kts"]
config    = [
          "settings.gradle.kts", "build.gradle.kts", "gradle.properties",
          ".sdkmanrc"
]
prefix    = "kt_"
active    = []

[polyglot.kotlin_jacamo]
suffixes  = [".asl", ".jcm"]
config    = []
active    = []

[polyglot.prolog]
suffixes  = [".pl"]
config    = []
prefix    = "pl_"
active    = []

[polyglot.rocq]
suffixes  = [".v"]
config    = ["_CoqProject"]
prefix    = "rq_"
active    = []

[polyglot.z3]
suffixes  = [".z3"]
config    = []
prefix    = "z3_"
active    = []

[polyglot.octave]
suffixes  = [".m"]
config    = []
prefix    = "oct_"
active    = []

[polyglot.bash]
suffixes  = [".bash"]
config    = [".shellcheckrc"]
prefix    = "sh_"
active    = []

[polyglot.supercollider]
suffixes  = [".scd"]
config    = []
prefix    = "sc_"
active    = []

[polyglot.plantuml]
suffixes  = [".pu"]
config    = []
active    = []

[polyglot.opa]
suffixes  = [".rego"]
config    = []
prefix    = "opa_"
active    = []

[polyglot.soar]
suffixes  = [".soar", ".vsa"]
config    = []
prefix    = "soar_"
active    = []


#  Docgen --------------------------------------------------

[polyglot.docgen.mdbook]
suffixes  = ["book.toml"]
config    = []
active    = []
dirs      = ["_book"]

[polyglot.docgen.sphinx]
suffixes  = [".rst"]
config    = ["src/_sphinx/conf.py"]
dirs      = ["_sphinx"]
active    = []

[polyglot.docgen.docfx]
suffixes  = [".md", ".yml"]
config    = ["docfx.json"]
dirs      = ["_docfx"]
active    = []

[polyglot.docgen.tex]
suffixes  = [".tex", ".bib"]
config    = ["init.tex.lua", "tex.reqs"]
dirs      = ["_tex"]
active    = []

[polyglot.docgen.changelog]
suffixes  = []
config    = ["towncrier.toml"]
files     = ["CHANGELOG.md"]
dirs      = ["_changes"]
active    = []

[polyglot.docgen.readthedocs]
config = [".reaadthedocs.yaml"]
