#  polyglot.toml -*- mode: toml-ts-mode -*-
#  Summary: Describes polyglot settings
#
#  '{}' in a string refers to the project name
#  eg: project 'blah', {}.sln -> blah.sln
#
#  Each entry can contain:
#  files[list], dirs[list], config[list]
#  suffixes[list], prefix[str]
#  active[list]
#  ignore[list]
#  -- 
#
#  'ignore' provides a list of patterns to add/remove to a gitignore file.
#  Tags:
#

[polyglot]
# For settings

[polyglot.aliases]



[polyglot.general]
files = [
  "polyglot.toml", "VERSION.toml", "LICENSE",
  ".lenvs", ".gitignore", ".editorconfig",
  ".rgignore", "checklist.md", ".related",
  "repo-layout.md"
]
dirs  = [
      ".tasks", ".temp", "src/_notes",
      "src/_tests", "src/_data"
]

#  Environment --------------------------------------------------

[polyglot.direnv]
config = [".envrc"]

[polyglot.asdf]
files = [".asdf.plugins", ".tool-versions"]

#  CI Workflows --------------------------------------------------

[polyglot.github]
dirs = [".github"]

[polyglot.gitlab]
files = [".gitlab-ci.yml"]
dirs  = [".gitlab"]

[polyglot.precommit]
files = [".pre-commit-config.yaml"]

[polyglot.tox]
files  = ["tox.toml"]

#  Languages --------------------------------------------------



#  Docgen    --------------------------------------------------


#  End       --------------------------------------------------
