[project]
name             = "{{cookiecutter.proj_name}}_lib"
version          = "0.1.0"
description      = "Add your description here"
readme           = "README.md"
requires-python  = ">={{cookiecutter.python}}"
dependencies     = []
